all:
  configuration:
    drm:
      negoce: true
      details:
        export_detail:
          required: ["identifiant"]
        vrac_detail:
          creation: true
      export_pays_debut: { }
      export_pays_fin: { "AUTRE": "Autres pays"}
      vrac_multi_produit: false
      crd_only_suspendus: false
