# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: global, action: home}

header:
  url: /header
  param: {module: global, action: header}

# TELEDECLARATION

auth_login_no_cas:
  url:   /login_no_cas
  param: { module: auth, action: login}


auth_logout:
  url:   /logout
  param: { module: auth, action: logout}

