# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow
    #viewport:      width=device-width, initial-scale=1.0

  stylesheets:    [compile.css?201806181116]

  javascripts:    [lib/jquery-1.7.2.min.js, lib/modernizr-2.js]

  has_layout:     true
  layout:         layout

  components:
    colContacts: [societe, getInterlocuteurs]
