all:
  configuration:
    facture:
      pdf_nom_interpro: "IVSO"
      pdf_ordre_cheque: "Interprofession des Vins du Sud Ouest"
      prefix_sage: "02"
      tva_compte: "44571502"
      defaut_compte: "70610000"
      type_cvo:
        identifiant_prefix: "C"
      type_libre:
        identifiant_prefix: "L"
      idcontrat: "ID"
      stockage_code_produit: "code_compte"
      pdf_produit: false
      pdf_nom_ref_client: "NÂ° IVSO"
      pdf_nom_taux: "Taux"
      pdf_display_code_comptable: true
      echeance: "+30 days"
      export_shell: "%sf_root_dir%/bin/exportSage.sh"
